import { spawnSync } from 'child_process';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import os from 'os';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const androidDir = path.join(root, 'android');

function existsJava(home) {
  if (!home) return false;
  return fs.existsSync(path.join(home, 'bin', 'java.exe')) || fs.existsSync(path.join(home, 'bin', 'java'));
}

function javaMajor(home) {
  const exe = fs.existsSync(path.join(home, 'bin', 'java.exe'))
    ? path.join(home, 'bin', 'java.exe')
    : path.join(home, 'bin', 'java');
  const r = spawnSync(exe, ['-version'], { encoding: 'utf8' });
  const text = `${r.stderr || ''}\n${r.stdout || ''}`;
  const m = text.match(/version "(\d+)(?:\.(\d+))?/);
  if (!m) return 0;
  const major = Number(m[1]);
  return major === 1 ? Number(m[2] || 0) : major;
}

function findJdk17() {
  const homes = [
    path.join(root, '.tools', 'jdk-17'),
    process.env.JAVA_HOME,
    'D:\\IntelliJ IDEA 2024.1.4\\jbr',
    'C:\\Program Files\\Android\\Android Studio\\jbr',
    'C:\\Program Files\\Java\\jdk-17',
    'C:\\Program Files\\Eclipse Adoptium\\jdk-17',
    'C:\\Program Files\\Microsoft\\jdk-17',
  ].filter(Boolean);

  try {
    const pf = 'C:\\Program Files\\Java';
    if (fs.existsSync(pf)) {
      for (const name of fs.readdirSync(pf)) {
        if (/jdk-1[7-9]|jdk-2/i.test(name)) homes.push(path.join(pf, name));
      }
    }
  } catch {}

  for (const home of homes) {
    if (!existsJava(home)) continue;
    const major = javaMajor(home);
    if (major >= 17) return home;
    console.warn(`[android:debug] 跳过过旧 JDK ${home} (Java ${major || '?'})`);
  }
  return '';
}

function looksLikeSdk(dir) {
  if (!dir || !fs.existsSync(dir)) return false;
  return fs.existsSync(path.join(dir, 'platform-tools'))
    || fs.existsSync(path.join(dir, 'platforms'))
    || fs.existsSync(path.join(dir, 'build-tools'));
}

function findSdk() {
  const homes = [
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    path.join(root, '.tools', 'android-sdk'),
    'D:\\Android\\Sdk',
    'D:\\sdk',
    'C:\\Android\\Sdk',
    path.join(os.homedir(), 'AppData', 'Local', 'Android', 'Sdk'),
  ].filter(Boolean);
  for (const home of homes) {
    if (looksLikeSdk(home)) return home;
  }
  return '';
}

function writeLocalProperties(sdk) {
  const file = path.join(androidDir, 'local.properties');
  const escaped = sdk.replace(/\\/g, '\\\\').replace(/:/g, '\\:');
  fs.writeFileSync(file, `# Generated by scripts/android-debug.mjs — do not commit\nsdk.dir=${escaped}\n`);
  console.log('[android:debug] sdk.dir ->', sdk);
}

function run(cmd, args, extraEnv) {
  const r = spawnSync(cmd, args, {
    cwd: extraEnv.cwd || root,
    env: extraEnv.env,
    stdio: 'inherit',
    shell: true,
  });
  if (r.status !== 0) process.exit(r.status || 1);
}

function gradleDistHash(url) {
  const md5 = crypto.createHash('md5').update(url, 'utf8').digest();
  return BigInt(`0x${md5.toString('hex')}`).toString(36);
}

function realGradleUserHome() {
  return path.join(root, '.tools', 'gradle');
}

function seedGradleWrapperZip() {
  const zip = path.join(root, '.tools', 'gradle-8.2.1-all.zip');
  if (!fs.existsSync(zip) || fs.statSync(zip).size < 10_000_000) return false;
  const raw = fs.readFileSync(path.join(androidDir, 'gradle', 'wrapper', 'gradle-wrapper.properties'), 'utf8');
  const m = raw.match(/distributionUrl=(.+)/);
  if (!m) return false;
  const url = m[1].trim().replace(/\\:/g, ':');
  const destDir = path.join(realGradleUserHome(), 'wrapper', 'dists', 'gradle-8.2.1-all', gradleDistHash(url));
  fs.mkdirSync(destDir, { recursive: true });
  const destZip = path.join(destDir, 'gradle-8.2.1-all.zip');
  if (!fs.existsSync(destZip) || fs.statSync(destZip).size !== fs.statSync(zip).size) {
    try {
      if (fs.existsSync(destZip)) fs.unlinkSync(destZip);
      fs.linkSync(zip, destZip);
    } catch {
      fs.copyFileSync(zip, destZip);
    }
  }
  for (const name of fs.readdirSync(destDir)) {
    if (name.endsWith('.part') || name.endsWith('.lck')) {
      try { fs.unlinkSync(path.join(destDir, name)); } catch {}
    }
  }
  console.log('[android:debug] Gradle zip ->', destZip);
  return true;
}

function prepareGradleEnv(env) {
  const home = realGradleUserHome();
  fs.mkdirSync(home, { recursive: true });
  env.GRADLE_USER_HOME = home;
  for (const k of ['HTTP_PROXY', 'HTTPS_PROXY', 'http_proxy', 'https_proxy', 'ALL_PROXY', 'all_proxy']) {
    delete env[k];
  }
  const bypass = '-Djava.net.useSystemProxies=false';
  env.GRADLE_OPTS = `${env.GRADLE_OPTS || ''} ${bypass}`.trim();
  env.JAVA_OPTS = `${env.JAVA_OPTS || ''} ${bypass}`.trim();
  console.log('[android:debug] GRADLE_USER_HOME ->', home);
}

const env = { ...process.env };
const jdk = findJdk17();
if (jdk) {
  env.JAVA_HOME = jdk;
  const bin = path.join(jdk, 'bin');
  const pathKey = env.Path ? 'Path' : 'PATH';
  env[pathKey] = `${bin}${path.delimiter}${env[pathKey] || ''}`;
  env.PATH = env[pathKey];
  env.Path = env[pathKey];
  console.log('[android:debug] JAVA_HOME ->', jdk);
} else {
  console.error(`
[android:debug] 没有找到 JDK 17+。不必安装 Android Studio 这个 IDE，但需要 JDK 17。
可选：
  1. 安装 Eclipse Temurin 17，并设置 JAVA_HOME
  2. 把便携 JDK 解压到 ${path.join(root, '.tools', 'jdk-17')}
当前 JAVA_HOME=${process.env.JAVA_HOME || '(未设置)'}
`);
  process.exit(1);
}

const sdk = findSdk();
if (!sdk) {
  console.error(`
[android:debug] 没有找到 Android SDK。不必打开 Android Studio 来点 Build，但机器上要有 SDK。
可选：
  1. 安装 Android Studio 一次，用它下载 SDK（默认在 %LOCALAPPDATA%\\Android\\Sdk）
  2. 只装 commandline-tools，设置 ANDROID_HOME，然后：
       sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
当前 ANDROID_HOME=${process.env.ANDROID_HOME || '(未设置)'}
`);
  process.exit(1);
}
env.ANDROID_HOME = sdk;
env.ANDROID_SDK_ROOT = sdk;
writeLocalProperties(sdk);

const version = bumpVersion();

console.log('[android:debug] 生成桌面图标…');
const icons = spawnSync('powershell', [
  '-NoProfile', '-ExecutionPolicy', 'Bypass',
  '-File', path.join(root, 'scripts', 'gen-icons.ps1'),
], { cwd: root, env, stdio: 'inherit' });
if (icons.status !== 0) {
  console.warn('[android:debug] 生成图标失败，继续打包（将使用已有/默认资源）');
}

run('npm', ['run', 'cap:sync'], { env });

prepareGradleEnv(env);
seedGradleWrapperZip();

const gradle = spawnSync('gradlew.bat', ['assembleDebug'], {
  cwd: androidDir,
  env,
  stdio: 'inherit',
  shell: true,
});
if (gradle.status !== 0) {
  console.error(`
[android:debug] Gradle 失败。常见原因：
  1. 本机代理 127.0.0.1:9910 没开
  2. Gradle 发行包没下完（把 gradle-8.2.1-all.zip 放到 ${path.join(root, '.tools')}）
`);
  process.exit(gradle.status || 1);
}

const apk = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk');
if (fs.existsSync(apk)) {
  console.log('\n[android:debug] APK:', apk);
  publishUpdate(apk, version);
  tryAdbInstall(sdk, apk);
} else {
  console.error('[android:debug] Gradle 结束了，但没找到 APK');
  process.exit(1);
}

function bumpVersion() {
  const file = path.join(androidDir, 'app', 'version.properties');
  let code = 1;
  if (fs.existsSync(file)) {
    const m = fs.readFileSync(file, 'utf8').match(/VERSION_CODE\s*=\s*(\d+)/);
    if (m) code = Number(m[1]);
  }
  code += 1;
  const name = `1.0.${code}`;
  fs.writeFileSync(file, `VERSION_CODE=${code}\nVERSION_NAME=${name}\n`);
  console.log(`[android:debug] versionCode -> ${code} (${name})`);
  return { code, name };
}

function publishUpdate(apkPath, ver) {
  const dir = path.join(root, 'backend', 'data', 'app-update');
  fs.mkdirSync(dir, { recursive: true });
  const dest = path.join(dir, 'nian.apk');
  fs.copyFileSync(apkPath, dest);
  const st = fs.statSync(dest);
  fs.writeFileSync(path.join(dir, 'version.json'), JSON.stringify({
    versionCode: ver.code,
    versionName: ver.name,
    size: st.size,
    builtAt: new Date().toISOString(),
  }, null, 2));
  console.log('[android:debug] 已挂到 backend/data/app-update ，手机连这个后端再进 App 会弹更新');
  console.log('[android:debug] 若后端在 VPS：把 backend/data/app-update 拷到服务器同路径即可，不用重启');
}

function tryAdbInstall(sdkHome, apkPath) {
  const adb = process.platform === 'win32'
    ? path.join(sdkHome, 'platform-tools', 'adb.exe')
    : path.join(sdkHome, 'platform-tools', 'adb');
  if (!fs.existsSync(adb)) return;
  const list = spawnSync(adb, ['devices'], { encoding: 'utf8' });
  const lines = `${list.stdout || ''}`.split(/\r?\n/).filter((l) => /\tdevice$/.test(l));
  if (!lines.length) {
    console.log('[android:debug] 没有已连接的 USB 调试设备，跳过 adb 安装');
    return;
  }
  console.log('[android:debug] 正在 adb 安装到手机…');
  const inst = spawnSync(adb, ['install', '-r', apkPath], { stdio: 'inherit', timeout: 180000 });
  if (inst.status === 0) console.log('[android:debug] adb 安装完成');
  else console.warn('[android:debug] adb 安装失败，可用应用内更新或手动装');
}
